version: '3.8'
services:
  web:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NEW_RELIC_LICENSE_KEY: NRAK-L07EBEGPZXGH6PQTB6AWDG5UXRO
      NEW_RELIC_APP_NAME: 'Blog Platform'
    command: npm start
